### ISSUE TITLE
Update endpoint for tor-client crx

### ISSUE THREAD

**Issue by jumde** [brave/go-update#33] opened 2020-01-23 21:23 UTC
For https://github.com/brave/devops/issues/2402

Tor Client updater for mac, windows and linux will be hosted at tor.bravesoftware.com. Update the endpoint for the client to fetch the correct binaries.

## TestPlan

1. On windows, linux and mac verify with a clean profile all components are downloaded correctly.
2. Restart the browser and confirm that no component update errors are displayed.
3. Verify the default components are working correctly

**Comment by LaurenWags** [comment] 2020-01-28 21:32
Verification **PASSED** on `macOS 10.14.6 x64` using builds that were created from https://github.com/brave/brave-core/pull/4428.

* Verified test plan from description above
   - Confirmed on a clean profile that all expected components were downloaded correctly
   - Confirmed all downloaded components worked as expected
   - No update errors observed on relaunch for components
* Using Little Snitch on clean profile on macOS, confirmed that only Brave/BraveSoftware domains were being connected to. Note - did see a connection to AWS, discussed with @jmude and this is due to using PR builder build.
* Verified able to use Tor window on clean profile. 
   - Confirmed I was able to visit .onion sites.
   - Confirmed using Tor network with check.torproject.org.
   - Confirmed getting new IP addresses worked as well for Tor windows
* Removed components, confirmed they were re-downloaded on relaunch.

**Comment by btlechowski** [comment] 2020-01-28 21:43
Verification passed on Ubuntu 18.04 LTS using build from https://github.com/brave/brave-core/pull/4428

- Verified test plan from the description
  - Verified that all components are downloaded on clean profile
  - Verified components works as expected
- Verified domains that the browser connects using Charles proxy. Found that the request header for tor binary does not contain `BraveServiceKey`
![image](https://user-images.githubusercontent.com/34715963/73307635-e19f7f80-421e-11ea-8666-b76a9bc0ffab.png)
- Verified Tor window works as expected (checked .onion sites and check.torproject.org)
- Verified WebTorrent component works by downloading a torrent.

**Comment by kjozwiak** [comment] 2020-01-28 21:50
Verification **PASSED** on `Win 10 x64` using the builds that were created from https://github.com/brave/brave-core/pull/4428.

* ensured that Brave doesn't connect to any third party domains on initial launch (used Fiddler) 
* ensured that `brave://components` doesn't display any `Errors` after restarting Brave several times
* ensured that all components are being re-downloaded if removed when Brave launches
* ensured that Tor is working as expected when opening a new Tor Window with a clean profile
  * ensured https://protonirockerxow.onion/ resolved without any issues
  * ensured https://check.torproject.org/ resolved without any issues
  * ensured that hard refreshing https://check.torproject.org/ retrieves a new IP/Tor Connection

```
Jan 28 16:13:17.281 [notice] Tor 0.3.5.8 running on Windows 8 [or later] with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jan 28 16:13:17.283 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning     Jan 28 16:13:17.285 [notice] Configuration file "C:\nonexistent" not present, using reasonable defaults.
Jan 28 16:13:17.287 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files (x86)\BraveSoftware\Brave-Browser-Nightly\Application\79.1.5.64\<default>. Is this what you wanted?
Jan 28 16:13:17.288 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files (x86)\BraveSoftware\Brave-Browser-Nightly\Application\79.1.5.64\<default>. Is this what you wanted?
Jan 28 16:13:17.290 [notice] Opening Socks listener on 127.0.0.1:9380
Jan 28 16:13:17.290 [notice] Opened Socks listener on 127.0.0.1:9380
Jan 28 16:13:17.291 [notice] Opening Control listener on 127.0.0.1:0
Jan 28 16:13:17.291 [notice] Control listener listening on port 51456.
Jan 28 16:13:17.291 [notice] Opened Control listener on 127.0.0.1:0
```

**Closed** 2020-01-29 17:47 UTC
